// class written by chatGTP (the idea of obfuscating the key was the Author's)

package utility;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.prefs.Preferences;





/**
 * Utility class for AES encryption and decryption with persistent key storage.
 *
 * <p>This class provides high-level static methods to encrypt and decrypt data using the
 * AES algorithm in CBC mode with PKCS5 padding. A persistent symmetric key is stored using
 * the {@link java.util.prefs.Preferences} API, allowing reuse across application restarts
 * without hardcoding sensitive key material directly in code.</p>
 *
 * <h2>Key Management</h2>
 * <ul>
 *   <li>The AES key is 128-bit (16 characters)</li>
 *   <li>If no key is present on first access, a default key is stored in preferences</li>
 *   <li>Users can override the key via {@link #setKey(String)}</li>
 * </ul>
 *
 * <h2>Encryption/Decryption Model</h2>
 * <ul>
 *   <li>Uses AES/CBC/PKCS5Padding cipher transformation</li>
 *   <li>A new 16-byte random IV is generated for every encryption</li>
 *   <li>The IV is prepended to the ciphertext for correct decryption</li>
 * </ul>
 *
 * <h2>Security Considerations</h2>
 * <ul>
 *   <li>For production-grade systems, external key management (e.g., KeyStore, KMS) is preferred</li>
 *   <li>The use of {@link Preferences} to store the AES key provides obfuscation, not encryption</li>
 * </ul>
 *
 * <h2>Example Usage</h2>
 * <pre>{@code
 * // Encrypt a message
 * String cipherText = CryptoUtils.encrypt("secret message".getBytes(StandardCharsets.UTF_8));
 *
 * // Decrypt the message
 * byte[] plainBytes = CryptoUtils.decrypt(cipherText);
 * String message = new String(plainBytes, StandardCharsets.UTF_8);
 * }</pre>
 *
 * @author Franco Della Negra
 * @version 1.0
 * @since 1.0
 */
public class CryptoUtils {
	
    /**
     * AES encryption algorithm specification: AES with CBC mode and PKCS5 padding.
     */
    private static final String ALGORITHM = "AES/CBC/PKCS5Padding";
    
    /**
     * Preference key used to persist and retrieve the AES encryption key.
     */
    private static final String PREFS_KEY = "aes_key";
    
    /**
     * Default fallback key used if none is already stored in preferences.
     * <p><strong>Note:</strong> This should be changed in future app expansions.</p>
     */
    private static final String DEFAULT_KEY = "16CharSecretKey!"; // 16 chars = 128 bits

    
    
    
    /**
     * Retrieves the persistent AES key from user preferences or initializes it with a default.
     *
     * @return a 128-bit AES {@link SecretKey}
     * @throws Exception if the key is invalid or preferences access fails
     */
    private static SecretKey getSecretKey() throws Exception {
        Preferences prefs = Preferences.userNodeForPackage(CryptoUtils.class);
        String keyString = prefs.get(PREFS_KEY, null);

        // If not set, set a default key (or prompt user, or generate random)
        if (keyString == null) {
            prefs.put(PREFS_KEY, DEFAULT_KEY);
            keyString = DEFAULT_KEY;
        }

        if (keyString.length() != 16) {
            throw new IllegalStateException("AES key must be 16 characters long.");
        }
        return new SecretKeySpec(keyString.getBytes(), "AES");
    }

    
    /**
     * Encrypts the given byte array using AES-CBC and returns a Base64-encoded ciphertext.
     *
     * <p>A 16-byte random IV is generated for each encryption and prepended to the ciphertext.</p>
     *
     * @param data the plaintext data to encrypt
     * @return the Base64-encoded IV + ciphertext
     * @throws Exception if the encryption fails
     */
    public static String encrypt(byte[] data) throws Exception {
        SecretKey key = getSecretKey();
        Cipher cipher = Cipher.getInstance(ALGORITHM);
        byte[] iv = new byte[16];
        new SecureRandom().nextBytes(iv);
        cipher.init(Cipher.ENCRYPT_MODE, key, new IvParameterSpec(iv));
        byte[] encrypted = cipher.doFinal(data);
        byte[] combined = new byte[iv.length + encrypted.length];
        System.arraycopy(iv, 0, combined, 0, iv.length);
        System.arraycopy(encrypted, 0, combined, iv.length, encrypted.length);
        return Base64.getEncoder().encodeToString(combined);
    }

    
    /**
     * Decrypts a Base64-encoded ciphertext previously generated by {@link #encrypt(byte[])}.
     *
     * <p>This method extracts the IV from the input, reinitializes the cipher with it, and
     * decrypts the remaining ciphertext.</p>
     *
     * @param encrypted the Base64-encoded IV + ciphertext
     * @return the original plaintext as a byte array
     * @throws Exception if decryption fails or key/IV are invalid
     */
    public static byte[] decrypt(String encrypted) throws Exception {
        byte[] combined = Base64.getDecoder().decode(encrypted);
        byte[] iv = new byte[16];
        byte[] encryptedBytes = new byte[combined.length - 16];
        System.arraycopy(combined, 0, iv, 0, 16);
        System.arraycopy(combined, 16, encryptedBytes, 0, encryptedBytes.length);
        SecretKey key = getSecretKey();
        Cipher cipher = Cipher.getInstance(ALGORITHM);
        cipher.init(Cipher.DECRYPT_MODE, key, new IvParameterSpec(iv));
        return cipher.doFinal(encryptedBytes);
    }

    
    
    /**
     * Replaces the current encryption key with a new 128-bit (16-character) key.
     *
     * <p>This operation overwrites the key stored in user preferences and will affect
     * decryption of all previously encrypted data unless the key is preserved externally.</p>
     *
     * @param newKey the new key to store; must be exactly 16 characters
     * @throws IllegalArgumentException if the key is invalid
     */
    public static void setKey(String newKey) {
        if (newKey == null || newKey.length() != 16) {
            throw new IllegalArgumentException("AES key must be 16 characters long.");
        }
        Preferences prefs = Preferences.userNodeForPackage(CryptoUtils.class);
        prefs.put(PREFS_KEY, newKey);
    }
}
